require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SwimsController do

  # This should return the minimal set of attributes required to create a valid
  # Swim. As you add validations to Swim, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      :swam_on => Date.today,
      :pool_id => 1,
      :kilometers => 1.0
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SwimsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all swims as @swims" do
      swim = Swim.create! valid_attributes
      get :index, {}, valid_session
      assigns(:swims).should eq([swim])
    end
  end

  describe "GET show" do
    it "assigns the requested swim as @swim" do
      swim = Swim.create! valid_attributes
      get :show, {:id => swim.to_param}, valid_session
      assigns(:swim).should eq(swim)
    end
  end

  describe "GET new" do
    it "assigns a new swim as @swim" do
      get :new, {}, valid_session
      assigns(:swim).should be_a_new(Swim)
    end
  end

  describe "GET edit" do
    it "assigns the requested swim as @swim" do
      swim = Swim.create! valid_attributes
      get :edit, {:id => swim.to_param}, valid_session
      assigns(:swim).should eq(swim)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Swim" do
        expect {
          post :create, {:swim => valid_attributes}, valid_session
        }.to change(Swim, :count).by(1)
      end

      it "assigns a newly created swim as @swim" do
        post :create, {:swim => valid_attributes}, valid_session
        assigns(:swim).should be_a(Swim)
        assigns(:swim).should be_persisted
      end

      it "redirects to the created swim" do
        post :create, {:swim => valid_attributes}, valid_session
        response.should redirect_to(Swim.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved swim as @swim" do
        # Trigger the behavior that occurs when invalid params are submitted
        Swim.any_instance.stub(:save).and_return(false)
        post :create, {:swim => {}}, valid_session
        assigns(:swim).should be_a_new(Swim)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Swim.any_instance.stub(:save).and_return(false)
        post :create, {:swim => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested swim" do
        swim = Swim.create! valid_attributes
        # Assuming there are no other swims in the database, this
        # specifies that the Swim created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Swim.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => swim.to_param, :swim => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested swim as @swim" do
        swim = Swim.create! valid_attributes
        put :update, {:id => swim.to_param, :swim => valid_attributes}, valid_session
        assigns(:swim).should eq(swim)
      end

      it "redirects to the swim" do
        swim = Swim.create! valid_attributes
        put :update, {:id => swim.to_param, :swim => valid_attributes}, valid_session
        response.should redirect_to(swim)
      end
    end

    describe "with invalid params" do
      it "assigns the swim as @swim" do
        swim = Swim.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Swim.any_instance.stub(:save).and_return(false)
        put :update, {:id => swim.to_param, :swim => {}}, valid_session
        assigns(:swim).should eq(swim)
      end

      it "re-renders the 'edit' template" do
        swim = Swim.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Swim.any_instance.stub(:save).and_return(false)
        put :update, {:id => swim.to_param, :swim => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested swim" do
      swim = Swim.create! valid_attributes
      expect {
        delete :destroy, {:id => swim.to_param}, valid_session
      }.to change(Swim, :count).by(-1)
    end

    it "redirects to the swims list" do
      swim = Swim.create! valid_attributes
      delete :destroy, {:id => swim.to_param}, valid_session
      response.should redirect_to(swims_url)
    end
  end

end
